title: Ahmed E. Mansour
description: Personal website and research profile for Ahmed E. Mansour.
theme: jekyll-theme-cayman
plugins: []

exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - vendor/
  - README.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
