remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Ahmed E. Mansour
description: Personal website
navbar:
-name: Home
  link:/index.html/
-name: Resume
  link:/resume.html/
-name: Research/
  link:/research.html
-name: publications:
  link:/contact.html/
