remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Ahmed E. Mansour
description: This is a personal webpage for Dr. Mansour

# Navigation Bar Links
navigation:
  - name: "Home"
    link: /
  - name: "Projects"
    link: /projects/
  - name: "Publications"
    link: /blog/
  - name: "Research experience"
    link: /about/
